services:
  service_registry:
    build:
      context: .
      dockerfile: DockerFileSR
    hostname: service_registry
    ports:
      - "50051:50051"

  peer-1:
    build:
      context: .
      dockerfile: DockerFileNode
    hostname: peer-1
    environment:
      - PEER_NAME=peer-1
      - PEER_BALANCE=1600
    ports:
      - "50052"
    depends_on:
      - service_registry
    volumes:
      - ./config.json:/config.json
    deploy:
      replicas: 2

  peer-2:
    build:
      context: .
      dockerfile: DockerFileNode
    hostname: peer-2
    environment:
      - PEER_NAME=peer-2
      - PEER_BALANCE=1200
    ports:
      - "50053"
    depends_on:
      - service_registry
      - peer-1
    volumes:
      - ./config.json:/config.json
    deploy:
      replicas: 2

  peer-3:
    build:
      context: .
      dockerfile: DockerFileNode
    hostname: peer-3
    environment:
      - PEER_NAME=peer-3
      - PEER_BALANCE=800
    ports:
      - "50054"
    depends_on:
      - service_registry
      - peer-1
      - peer-2
    volumes:
      - ./config.json:/config.json
    deploy:
      replicas: 2

  client:
    build:
      context: .
      dockerfile: DockerFileClient
    hostname: client
    environment:
      - SENDER=peer-1
      - RECEIVER=peer-3
      - AMOUNT=500
    depends_on:
      - peer-1
      - peer-2
      - peer-3